development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: le_development
  pool: 5
  username: le
  password:
  socket: /tmp/mysql.sock
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
